apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: jenkins.m4lcherczyk.com
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: admin@example.com
      enabled: true
      production: false
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
